import libs += libboost-lexical-cast%lib{boost_lexical_cast}

lib{text-archive}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBTEXT_ARCHIVE_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBTEXT_ARCHIVE_SHARED_BUILD

# Export options.
#
lib{text-archive}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{text-archive}: cxx.export.poptions += -DLIBTEXT_ARCHIVE_STATIC
libs{text-archive}: cxx.export.poptions += -DLIBTEXT_ARCHIVE_SHARED

if $version.pre_release
  lib{text-archive}: bin.lib.version = "-$version.project_id"
else
  lib{text-archive}: bin.lib.version = "-$version.major.$version.minor"

{hxx ixx txx}{*}:
{
  install         = include/libtext-archive/
  install.subdirs = true
}
